version: '3.8'

services:
  # Database Service
  inc-db:
    image: mysql:8.0
    container_name: inc-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - inc_mysql_data:/var/lib/mysql

  inc-backend:
    build: ./backend
    container_name: inc-backend
    restart: always
    env_file: .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=inc-db  # Internal Docker DNS name
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - inc-db

  inc-frontend:
    build:
      context: .
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: inc-frontend
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - inc-backend

volumes:
  inc_mysql_data: